import React from 'react';

const TermsAndConditions = () => {
  return (
    <div className="container mx-auto p-4">
      <h1 className="text-3xl font-bold mb-4">Terms and Conditions</h1>
      <p className="mb-4"><strong>Last Updated: [Date]</strong></p>

      <p>Welcome to [AI Art Generator] ("we", "our", "us"). By using our AI art generator application (the "Service"), you agree to these Terms and Conditions. If you do not agree, please do not use our Service.</p>

      <h2 className="text-2xl font-semibold mt-4">1. Acceptance of Terms</h2>
      <p>By accessing or using our Service, you agree to be bound by these Terms. If you are using the Service on behalf of a company or other entity, you represent that you have the authority to bind that entity to these Terms.</p>

      <h2 className="text-2xl font-semibold mt-4">2. Changes to Terms</h2>
      <p>We may modify these Terms from time to time. If we do, we will provide notice of the changes, such as by posting a notice on our website or sending you an email. Your continued use of the Service after any changes indicates your acceptance of the new Terms.</p>

      <h2 className="text-2xl font-semibold mt-4">3. User Accounts</h2>
      <p>To access certain features of the Service, you may need to create an account. You are responsible for maintaining the confidentiality of your account information and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.</p>

      <h2 className="text-2xl font-semibold mt-4">4. User Conduct</h2>
      <p>You agree to use the Service only for lawful purposes and in accordance with these Terms. You agree not to use the Service:</p>
      <ul className="list-disc ml-6">
        <li>To generate content that is illegal, obscene, or harmful.</li>
        <li>To impersonate any person or entity, or misrepresent your affiliation with any person or entity.</li>
        <li>To interfere with or disrupt the security, integrity, or performance of the Service.</li>
      </ul>

      <h2 className="text-2xl font-semibold mt-4">5. Ownership of Content</h2>
      <p>All content generated through the Service is the property of [Your App Name]. However, you retain ownership of any input you provide to the Service. By using the Service, you grant us a non-exclusive, royalty-free, worldwide, perpetual license to use, reproduce, modify, and display the content generated by the Service.</p>

      <h2 className="text-2xl font-semibold mt-4">6. Intellectual Property Rights</h2>
      <p>The Service and its original content, features, and functionality are and will remain the exclusive property of [Your App Name] and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries.</p>

      <h2 className="text-2xl font-semibold mt-4">7. Disclaimers</h2>
      <p>The Service is provided on an "as-is" and "as-available" basis. We make no warranties of any kind, whether express or implied, regarding the operation of the Service or the information, content, materials, or products included in the Service.</p>

      <h2 className="text-2xl font-semibold mt-4">8. Limitation of Liability</h2>
      <p>To the fullest extent permitted by law, [Your App Name] shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from or related to your use of the Service.</p>

      <h2 className="text-2xl font-semibold mt-4">9. Indemnification</h2>
      <p>You agree to indemnify, defend, and hold harmless [Your App Name], its affiliates, and their respective officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, or expenses arising out of or related to your use of the Service.</p>

      <h2 className="text-2xl font-semibold mt-4">10. Governing Law</h2>
      <p>These Terms shall be governed by and construed in accordance with the laws of [Your State/Country], without regard to its conflict of law principles.</p>

      <h2 className="text-2xl font-semibold mt-4">11. Contact Us</h2>
      <p>If you have any questions about these Terms, please contact us at [Your Contact Information].</p>
    </div>
  );
};

export default TermsAndConditions;